###
POST http://localhost:9000/api/users HTTP/1.1
content-type: application/json

{
    "nombre": "Pepa7",
    "apellido": "Pig",
    "identificacion":1111111111,
    "correoElectronico":"pepa@pig"
}
###
GET http://localhost:9000/api/users HTTP/1.1
content-type: application/json

###
GET http://localhost:9000/api/users/identificacion/1111111111 HTTP/1.1
content-type: application/json

###
PUT http://localhost:9000/api/users/identificacion/1111111111
Content-Type: application/json

{
    "nombre": "Peppa",
    "apellido": "Pig",
    "identificacion": 1111111111,
    "correoElectronico": "pepa@pig"
}

###
DELETE  http://localhost:9000/api/users/identificacion/1111111111

###
POST http://localhost:9000/api/bibliotecas HTTP/1.1
content-type: application/json

{
    "titulo": "Probando, probando",
    "fechaCreacion": "2024-09-09",
    "fechaVencimiento": "2025-01-31",
    "valorTotal": 1000500,
    "tipo": "IVA",
    "estado": "creados por mí",
    "formato":"imágen"
}