###
POST http://localhost:9000/api/users HTTP/1.1
content-type: application/json

{
    "nombre": "Pepa",
    "apellido": "Pig",
    "identificacion":1111111111,
    "correoElectronico":"pepa@pig"
}
###
GET http://localhost:9000/api/users HTTP/1.1
content-type: application/json

###
GET http://localhost:9000/api/users/identificacion/1111111111 HTTP/1.1
content-type: application/json

###
PUT http://localhost:9000/api/users/identificacion/1111111111
Content-Type: application/json

{
    "nombre": "Peppa",
    "apellido": "Pig",
    "identificacion": 1111111111,
    "correoElectronico": "pepa@pig"
}

###
DELETE  http://localhost:9000/api/users/identificacion/1111111111

###
POST http://localhost:9000/api/bibliotecas HTTP/1.1
content-type: application/json

{
    "tipo": "IVA",
    "etiqueta": "",
    "fechaCreacion":1111111111,
    "horaCreacion":"pepa@pig",
    "fechaVencimiento":1111111111,
    "horaVencimiento":"pepa@pig",
    "comentario":"nn"
}